### ISSUE TITLE
Wire Hided or Showed

### ISSUE THREAD

**Issue by Spirou4D** [Korchy/blender-wire#1]
I have one question, please: Why to addon with the same name of class and shortcuts?
The both don't run together in same time?

Why not two classes and two shortcuts to use both together?

**Comment by Korchy** [comment]
You dont need to use both WireH and WireS. They do the same sing. I recommend to use only WireS.

I made WireH class when i couldnt solve a problem of correctly clearing meshs edges after wireframe render. This variant is an alternative - hidden render process but correcly clearing edges after render.

Now this problem is solved and WireS dont hide render process and correctly clears all data after finishing its work. So it is more comfortable to use it.

**Comment by Spirou4D** [comment]
Ok Nikita,
Thanks a lot for your very speed answer, Nice!
I understand your reasons. Fine.

Congratulations for your quick render wire addon.
good Luck.
Spirou4D

---

Patrick DepoixArchitecte D.P.L.G.Historien-chercheur en histoire de
l'ArchitectureEx-Maître de conférence de l'Ecole d'Architecture de
Lille-Région NordSitArchi-ReaderNewS
http://www.google.com/reader/shared/user%2F04161245489718164963%2Fstate%2Fcom.google%2Fstarred

http://www.linkedin.com/pub/patrick-depoix/40/b3b/542136, rue d'Esquermes59000
LilleFranceTel   (+33/0) 952 51 33 25Port  (+33/0) 06 23 13 73 71
Skype:oikakeruPour répondre --> Mailto:patrick.depoix@gmail.com
http://---%20http://www.linkedin.com/pub/patrick-depoix/40/b3b/542%20Patrick%20Depoix%20Architecte%20D.P.L.G.%20Historien-chercheur%20en%20histoire%20de%20l%27Architecture%20Ex-Ma%C3%AEtre%20de%20conf%C3%A9rence%20de%20l%27Ecole%20d%27Architecture%20de%20Lille-R%C3%A9gion%20Nord136,%20rue%20d%27Esquermes%2059000%20Lille%20France%20Tel%20%20%20%28+33/0%29%20952%2051%2033%2025%20Port%20%20%28+33/0%29%2006%2023%2013%2073%2071%20Fax%20%20%28+33/0%29%20826%2070%2004%2040%20Skype:oikakeru%20%20Pour%20r%C3%A9pondre%20--%3E%20Mailto:patrick.depoix@free.fr

2016-09-10 16:18 GMT+02:00 Nikita Akimov notifications@github.com:

**Comment by Spirou4D** [comment]
Hi Nikita,

I have find a problem with blender 2.78 last trunk release on my Linux Mint
17.3 64bytes:
You have forgotten to check this to false:
rd = context.scene.render
self.layout.prop(rd, "use_freestyle", text="")=False

The checkbox in the Render property panel stay activated after the use of
WireS.py

So when you render F12, you have always the edges because Freestyle is
always activated!

Good Luck
Byebye
Spirou4D

---

Patrick DepoixArchitecte D.P.L.G.Historien-chercheur en histoire de
l'ArchitectureEx-Maître de conférence de l'Ecole d'Architecture de
Lille-Région NordSitArchi-ReaderNewS
http://www.google.com/reader/shared/user%2F04161245489718164963%2Fstate%2Fcom.google%2Fstarred

http://www.linkedin.com/pub/patrick-depoix/40/b3b/542136, rue d'Esquermes59000
LilleFranceTel   (+33/0) 952 51 33 25Port  (+33/0) 06 23 13 73 71
Skype:oikakeruPour répondre --> Mailto:patrick.depoix@gmail.com
http://---%20http://www.linkedin.com/pub/patrick-depoix/40/b3b/542%20Patrick%20Depoix%20Architecte%20D.P.L.G.%20Historien-chercheur%20en%20histoire%20de%20l%27Architecture%20Ex-Ma%C3%AEtre%20de%20conf%C3%A9rence%20de%20l%27Ecole%20d%27Architecture%20de%20Lille-R%C3%A9gion%20Nord136,%20rue%20d%27Esquermes%2059000%20Lille%20France%20Tel%20%20%20%28+33/0%29%20952%2051%2033%2025%20Port%20%20%28+33/0%29%2006%2023%2013%2073%2071%20Fax%20%20%28+33/0%29%20826%2070%2004%2040%20Skype:oikakeru%20%20Pour%20r%C3%A9pondre%20--%3E%20Mailto:patrick.depoix@free.fr

2016-09-10 16:18 GMT+02:00 Nikita Akimov notifications@github.com:

**Comment by Korchy** [comment]
Strange. The freestyle checkbox deactivates in line 37

bpy.context.scene.render.use_freestyle = False

I use windows and cant test addon on linux (
On windows and Blender 2.77a i tested it again now - freestyle offs and next usual f12 render works correct.

**Comment by Spirou4D** [comment]
2016-09-10 17:33 GMT+02:00 Nikita Akimov notifications@github.com:

> bpy.context.scene.render.use_freestyle = False

yes I agree with you i try in console and
bpy.context.scene.render.use_freestyle=False
run well!
Wait a minute....

....I try again and now all run because I have remove the WireH.py!
It's certainly a function stay in memory.

 Excuse me all is ok now!
Bye
Spirou4D

---

Patrick DepoixArchitecte D.P.L.G.Historien-chercheur en histoire de
l'ArchitectureEx-Maître de conférence de l'Ecole d'Architecture de
Lille-Région NordSitArchi-ReaderNewS
http://www.google.com/reader/shared/user%2F04161245489718164963%2Fstate%2Fcom.google%2Fstarred

http://www.linkedin.com/pub/patrick-depoix/40/b3b/542136, rue d'Esquermes59000
LilleFranceTel   (+33/0) 952 51 33 25Port  (+33/0) 06 23 13 73 71
Skype:oikakeruPour répondre --> Mailto:patrick.depoix@gmail.com
http://---%20http://www.linkedin.com/pub/patrick-depoix/40/b3b/542%20Patrick%20Depoix%20Architecte%20D.P.L.G.%20Historien-chercheur%20en%20histoire%20de%20l%27Architecture%20Ex-Ma%C3%AEtre%20de%20conf%C3%A9rence%20de%20l%27Ecole%20d%27Architecture%20de%20Lille-R%C3%A9gion%20Nord136,%20rue%20d%27Esquermes%2059000%20Lille%20France%20Tel%20%20%20%28+33/0%29%20952%2051%2033%2025%20Port%20%20%28+33/0%29%2006%2023%2013%2073%2071%20Fax%20%20%28+33/0%29%20826%2070%2004%2040%20Skype:oikakeru%20%20Pour%20r%C3%A9pondre%20--%3E%20Mailto:patrick.depoix@free.fr
